{% set name = "tiffslide" %}
{% set version = "1.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3893d1b90ef0c132f8d9c87995c03d9ac6761f9fa58c362c04e2fc341960ec01

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - fsspec
    - imagecodecs
    - pillow
    - python >=3.7
    - tifffile >=2021.6.14
    - typing-extensions >=4.0
    - zarr

test:
  imports:
    - tiffslide
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bayer-science-for-a-better-life/tiffslide
  summary: A drop-in replacement for openslide-python.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ap--
    - sarthakpati
    - sdvillal
