{% set name = "tiffslide" %}
{% set version = "1.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0199dfdf30ac166385e2712c607f5ed1de0583800a34831a4bb80e5a0a47068b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - fsspec
    - imagecodecs
    - pillow
    - python >=3.7
    - tifffile >=2020.9.22
    - typing-extensions >=4.0
    - zarr

test:
  imports:
    - tiffslide
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bayer-science-for-a-better-life/tiffslide
  summary: A drop-in replacement for openslide-python.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ap--
    - sarthakpati
    - sdvillal
