{% set name = "tiffslide" %}
{% set version = "2.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 630bc36215e950dd9df279ded147cf129570f2040c7e3363cdf6845414da9672

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - fsspec !=2022.11.0,!=2023.1.0
    - imagecodecs
    - pillow
    - python >={{ python_min }}
    - tifffile >=2021.6.14
    - typing-extensions >=4.0
    - zarr >=2.11.0

test:
  imports:
    - tiffslide
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bayer-science-for-a-better-life/tiffslide
  summary: A drop-in replacement for openslide-python.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ap--
    - sarthakpati
    - sdvillal
