{% set name = "tiffslide" %}
{% set version = "1.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1b09032e0d865035088da091e1574445debad9526e5fafad3d16e1fd7195ff21

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools-scm
  run:
    - backports.cached-property  # [py<38]
    - fsspec
    - imagecodecs
    - importlib-metadata  # [py<38]
    - pillow
    - python
    - tifffile >=2020.9.22
    - typing-extensions  # [py<311]
    - zarr  # [py>37]
    - zarr <2.11.0  # [py<38]

test:
  imports:
    - tiffslide
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bayer-science-for-a-better-life/tiffslide
  summary: A drop-in replacement for openslide-python.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ap--
    - sarthakpati
    - sdvillal
